### PR TITLE
Botching just enough code to get it to work on our server

### PR DESCRIPTION
**Pull request by dequbed**
The biggest change this does is removing build numbers from `build.gradle` and ensuring gradle will preferably look for locally built libraries and only hit maven when it can't find any. That and ae72e62 ensured we could connect to our server.

a656176 and 1f646e8 are only there because I can't be bothered to remove them from this branch <3

### CODE REVIEW

**Comment by fnuecke** [comment]
~Hmm. Dedicated server starts fine for me as-is, and I don't see any obvious uses of client-side stuff in the recipe serializers.~

~Could you post your crash log?~

Oh, hang on, you said when connecting. Sorry. Can reproduce, looking into it.

**Comment by dequbed** [comment]
There isn't one. The server starts fine but trying to connect fails with an error inside getty.

**Comment by fnuecke** [comment]
Yeah, sorry, just realized. Looking into it.

**Comment by fnuecke** [comment]
All right, fixed! Thanks for letting me know :)

**Pull request closed without merging**
