### PR TITLE
Add Crafting to OC2

### LINKED ISSUE #2: Recipes
Things need recipes. Wanna keep it simple, let's say max depth of 3. One or two intermediary crafting materials, and that only to avoid conflicts.

### PR DESCRIPTION
**Pull request by lucsoft**
This will close https://github.com/fnuecke/oc2/issues/2

### CODE REVIEW

**Comment by lucsoft** [comment]
Okay im ready for merge (pls no squash 😉 )   
Note: Some Recipes required NBT data thats why 3 Recipes don't show in JEI or the Vanilla Recipe Book (this needs to be addressed later)

**Comment by SquidDev** [comment]
There's a couple of places it might be worth using item tags rather than requiring a specific item. Especially thinking of chests (quark adds chests for each wood type, which makes obtaining a "vanilla" chest a bit harder), but ingots/nuggets may be worthwhile too.

I'd personally also recommend using data generators for the recipes, but that might be unnecessary complexity for everyone :P.

**Comment by lucsoft** [comment]
@SquidDev yeah i will change to some tags & data generators(the data generators are not really well documented but i will try to convert it)

**Comment by lucsoft** [comment]
> Okay im ready for merge (pls no squash 😉 )
> Note: Some Recipes required NBT data thats why 3 Recipes don't show in JEI or the Vanilla Recipe Book (this needs to be addressed later)

okay now :D

**Comment by fnuecke** [comment]
Merged into the 1.16.5 branch now. Thanks again for prepping this :)

**Pull request closed without merging**
