### PR TITLE
add volume & pitch to sound card

### LINKED ISSUE #126: Support changing pitch & volume with the sound card
You should be able to play sounds of different pitches and volume with the soundcard, maybe as a second and third argument to the playSound command.

### PR DESCRIPTION
**Pull request by kore-signet**
fixes #126

### CODE REVIEW

**Comment by man-of-eel** [comment]
do you know if the pitch is limited to 0.5-2.0 like with the /playsound commmand?

**Comment by kore-signet** [comment]
i'd assume so

**Comment by fnuecke** [comment]
From what I can tell, the `SoundEngine` at the very end of the chain leading to the sound actually getting played clamps volume to [0, 1] and pitch to [0.5, 2]. So I'd leave clamping out here, to stay compatible with any potential future changes to these defaults.

**Comment by fnuecke** [comment]
Looks great, thanks!

**Pull request merged**
