### PR TITLE
Create zh_cn.json

### PR DESCRIPTION
**Pull request by mckuhei**

### CODE REVIEW

**Comment by CoolCat467** [comment]
Good luck mate. I tried to have a similar file submitted and they said translations were bad (probably are, but I don't speak almost any of the 21 I wanted added.) Don't trust google translate pretty much.

**Comment by mckuhei** [comment]
> Good luck mate. I tried to have a similar file submitted and they said translations were bad (probably are, but I don't speak almost any of the 21 I wanted added.) Don't trust google translate pretty much.

I translated it myself

**Comment by mckuhei** [comment]
@fnuecke merge pull request plz

**Comment by fnuecke** [comment]
Thanks :)

**Pull request merged**
