### PR TITLE
Add multiple language translations

### PR DESCRIPTION
**Pull request by CoolCat467**
Add Lolcat language translation with help from https://github.com/CoolCat467/Localization-Translation-Utility

### CODE REVIEW

**Comment by CoolCat467** [comment]
I could easily add many more translations, given the language code for that language and if google translate supports it. And of course, machine translations aren't the best in the world and can have problems, but still, at least it would be there.

**Comment by CoolCat467** [comment]
All commits with title "Fix formatted values" were fixing parts of text that would be formatted with numbers, like changing "% s / t" to "%s/t" like it's supposed to be.

**Review by lucsoft — CHANGES_REQUESTED** [review]
@CoolCat467 thanks for you PR but can you try to use DeepL 
by the looks of it some translations are a bit broken/wrong

**Review by CoolCat467 — COMMENTED** [review]
Double check of all text with formatted values looks good

**Comment by CoolCat467** [comment]
To be honest I don't know any of these languages myself, other than a little bit of French and Lolcat since it's basically just broken English. My idea is just to have these out there, and if people who actually use these languages notice problems with the translations they could come here and fix it, but at least its there to begin with.

I'll look into this DeepL thing you speak of and see if I could easily have a script use it.

**Comment by lucsoft** [comment]
I don't mean formatted values just the translation itself

DeepL is a bit better then google translator

> I'll look into this DeepL thing you speak of and see if I could easily have a script use it.

Well just use the values of the english translation put everything in a new line and deepl translates all of it

**Comment by CoolCat467** [comment]
I've found DeepL, looks nice and people say good things about it, but my problem is that it looks like it has limits on its free API. Google's official one does as well, but my script uses a API endpoint that doesn't need an API key, which is great for me because then I don't have to spend lots of money to help cool projects I find interesting. I'll do new translations through it manually, but it doesn't support as many languages as google translate.

**Comment by lucsoft** [comment]
there is https://www.npmjs.com/package/deepl-translator if you use javascript

**Comment by CoolCat467** [comment]
Python3

**Comment by CoolCat467** [comment]
Oh my...
  "tooltip.oc2.device_needs_reboot": "Requires reboot"
  "Requires reboot": "Requires reboot": "Requires reboot",

**Comment by CoolCat467** [comment]
Ok this is going to be a bit much for me to do all this manually. This is the sort of reason why I use google translate. No copy pasting and it still all works, even if the translation is a bit off. If someone else wants to use DeepL and they've bought an API key, go ahead and do it, but there's no way I'm doing that anytime soon. Plus, it appears to break at seemingly random places and have many duplicates of the same thing over and over again, so you have to manually fix it. Not fun.

**Comment by fnuecke** [comment]
I'm sorry, but just looking at the German one alone proves my strong (earned) dislike of machine translation for localization. In particular when it's single words without context. I strongly suspect the other languages don't fare much better.

I do appreciate the idea, and the time you put into this, but I don't plan on merging machine-translations.

**Comment by CoolCat467** [comment]
Alright, but I just thought it would be a good idea to have the basis of it there, and then people who actually use those languages can fix any grammatical or other errors introduced by the machine translation. Thank you for your time.

**Pull request closed without merging**
